### PR TITLE
Factory animation

### PR DESCRIPTION
**Pull request by irubido**
Screenshot 2020-10-26 at 16 54 36
Screenshot 2020-10-26 at 16 54 18
Screenshot 2020-10-26 at 16 54 06

### CODE REVIEW

**Comment by morrigan** [comment]
Maybe for mobile it should not overlap so much with text and button? Meaning it should be placed more below. cc @mpetrunic

**Comment by morrigan** [comment]
Screenshot 2020-10-26 at 17 06 40
Also, not good with very large screens (you can zoom out to render)

**Comment by mpetrunic** [comment]
Let's push it a bit down on mobile to reduce overlap

**Comment by irubido** [comment]
Screenshot 2020-10-27 at 09 51 34
Screenshot 2020-10-27 at 09 51 27
Screenshot 2020-10-27 at 09 51 07
Screenshot 2020-10-27 at 09 50 44

**Comment by morrigan** [comment]
Looks ok to me. It's bit ungrateful for mobile but current version of the position in the mobile doesn't seem to be better. That said, I think this is ok and I have no better ideas. cc  @mpetrunic

**Comment by mpetrunic** [comment]
fine by me

**Review by morrigan — APPROVED** [review]

**Pull request merged**
